### ISSUE TITLE
appdaemon_weatherentity-master.js - file not found error

### ISSUE THREAD

**Issue by CocaCooper** [vche/appdaemon_weatherentity#5]
Currently running AppDaemon4 (0.7.1) - HASSIO 2021.11.5

custom-widgets folder created inside:   /config/appdaemon/

2021-12-15 02:58:08.365607 INFO AppDaemon: Loading custom widget 'appdaemon_weatherentity-master'
2021-12-15 02:58:08.366979 WARNING AppDaemon: ------------------------------------------------------------
2021-12-15 02:58:08.368180 WARNING AppDaemon: Unexpected error during DASH creation
2021-12-15 02:58:08.369280 WARNING AppDaemon: ------------------------------------------------------------
2021-12-15 02:58:08.372184 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/dashboard.py", line 875, in get_dashboard
    dash = self._conditional_compile(name, skin, recompile)
  File "/usr/lib/python3.9/site-packages/appdaemon/dashboard.py", line 829, in _conditional_compile
    dash = self._get_dash(name, skin, skindir)
  File "/usr/lib/python3.9/site-packages/appdaemon/dashboard.py", line 641, in _get_dash
    widgets = self._get_widgets()
  File "/usr/lib/python3.9/site-packages/appdaemon/dashboard.py", line 736, in _get_widgets
    with open(jspath, "r") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/config/appdaemon/custom_widgets/appdaemon_weatherentity-master/appdaemon_weatherentity-master.js'

**Comment by vche** [comment]
It seems you didn't install the widget you just cloned it.

Use the provided script to install the files from the repo into your /config/appdaemon/ folder or refer to the appdaemon doc for installing custom widget
